---
- hosts: vms
  become: yes
  roles:
    - common
  tags:
    vms

- hosts: development
  become: yes
  roles:
#    - common
    - docker
#    - aws_cli2
    - java
  tags: 
    dev