---
- name: for Debian family installing must have packages
  apt: 
    name: " {{ java_version }} " 
    state: latest 
    update_cache: yes
  when: ansible_os_family == "Debian"
  async: 600
  poll: 5
  tags: installation

- name: for Redhat family installing must have packages
  yum: 
    name: " {{ java_version }} "
    state: latest 
    update_cache: yes
  when: ansible_os_family == "Redhat"
  async: 600
  poll: 5
  tags: installation
