---
- name: for Debian family installing must have packages
  apt: 
    name: ['mc','apache2-utils','net-tools']
    state: latest 
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: installation

- name: for Redhat family installing must have packages
  yum: 
    name: ['mc','apache2-utils','net-tools']
    state: latest 
    update_cache: yes
  when: ansible_os_family == "Redhat"
  tags: installation
